// CSE46D — Computer Architecture (Lovely Professional University).
// REBUILT per KUBE_LESSON_DEPTH.md: one concept per circle, four-quarter
// depth, one document at a time. All six units are fully built:
//   U1: Unit_1_1.pptx + Unit_12.pptx (sections A & B)
//   U2: Data_Tranfer_and_Manipulation.ppt (CPU half) + Addressing Modes deck (C)
//   U3: Data Transfer deck's image-based back half, read slide by slide (D)
//   U4: UNIT_4_CSE46D.ppt (E)   U5: Unit5_ppt.pptx (F)   U6: UNIT_6_ppt.pptx (G)
// The previous shallow sections live in git history (commit 105ba44).
import { buildCourseBundle } from "./bundle";
import type { ExamQuestion, SyllabusInfo } from "./types";
import { sectionU1A } from "./cse46d-unit1a";
import { sectionU1B } from "./cse46d-unit1b";
import { sectionU2 } from "./cse46d-unit2";
import { sectionU3 } from "./cse46d-unit3";
import { sectionU4 } from "./cse46d-unit4";
import { sectionU5 } from "./cse46d-unit5";
import { sectionU6 } from "./cse46d-unit6";

export const cse46dSyllabus: SyllabusInfo = {
  units: [
    { unit: 1, title: "Data representation" },
    { unit: 2, title: "Central processing unit" },
    { unit: 3, title: "Stack Organization" },
    { unit: 4, title: "Computer Arithmetic" },
    { unit: 5, title: "Input-Output organization" },
    { unit: 6, title: "Memory organization" },
  ],
  cos: [
    { id: "CO1", text: "Understand different number systems (decimal, binary, octal, hexadecimal) and their conversions." },
    { id: "CO2", text: "Explain the addressing modes and their importance in instruction execution." },
    { id: "CO3", text: "Describe the role of program control instructions in sequence and flow of execution." },
    { id: "CO4", text: "Describe the basics of addition and subtraction operations in binary systems." },
    { id: "CO5", text: "Explain the concepts of Input-Output interfaces and asynchronous data transfer." },
    { id: "CO6", text: "Understand the memory hierarchy and its impact on system performance." },
  ],
};

const examBank: ExamQuestion[] = [
  // ---- Authored for Unit 1's circles (CO1/CO2 per syllabus mapping) ----
  {
    id: "ca-u1q1", topicId: "ca-hex", unit: 1, co: "CO1", level: "L1", source: "generated",
    prompt: "The base (radix) of the hexadecimal number system is…",
    options: ["8", "10", "16", "2"], answer: 2,
    hint: "Count its symbols: 0–9 and A–F.",
    explanation: "Hexadecimal uses sixteen symbols (0–9, A–F), so its base is 16.",
  },
  {
    id: "ca-u1q2", topicId: "ca-bits", unit: 1, co: "CO1", level: "L1", source: "generated",
    prompt: "Which group of bits is called a byte?",
    options: ["2 bits", "4 bits", "8 bits", "16 bits"], answer: 2,
    hint: "A nibble is half of it.",
    explanation: "A byte is 8 bits; a nibble is 4. MSB/LSB name its end bits.",
  },
  {
    id: "ca-u1q3", topicId: "ca-to-decimal", unit: 1, co: "CO1", level: "L2", source: "generated",
    prompt: "(1101)₂ equals which decimal number?",
    options: ["11", "13", "14", "9"], answer: 1,
    hint: "Place values from the right: 1, 2, 4, 8.",
    explanation: "8 + 4 + 0 + 1 = 13 — multiply each bit by its power of 2 and add.",
  },
  {
    id: "ca-u1q4", topicId: "ca-to-decimal", unit: 1, co: "CO1", level: "L2", source: "generated",
    prompt: "(124)₈ in decimal is…",
    options: ["84", "124", "96", "72"], answer: 0,
    hint: "Powers of 8: 64, 8, 1.",
    explanation: "1×64 + 2×8 + 4×1 = 84. Same place-value method, base 8.",
  },
  {
    id: "ca-u1q5", topicId: "ca-group-shortcuts", unit: 1, co: "CO1", level: "L2", source: "generated",
    prompt: "Converting binary to octal uses groups of…",
    options: ["4 bits from the left", "3 bits from the right", "8 bits", "2 bits"], answer: 1,
    hint: "8 = 2³.",
    explanation: "Each octal digit covers exactly 3 bits (2³ = 8), grouped from the LSB end with left padding.",
  },
  {
    id: "ca-u1q6", topicId: "ca-twos-comp", unit: 1, co: "CO1", level: "L2", source: "generated",
    prompt: "The 2's complement of 01100 is…",
    options: ["10011", "10100", "01101", "11100"], answer: 1,
    hint: "Flip everything, then add 1.",
    explanation: "1's complement 10011, plus 1 gives 10100. Flip-then-add-one, always.",
  },
  {
    id: "ca-u1q7", topicId: "ca-sign-magnitude", unit: 1, co: "CO1", level: "L1", source: "generated",
    prompt: "In signed binary the sign bit is…",
    options: [
      "the rightmost bit; 1 means positive",
      "the leftmost bit; 0 means positive and 1 means negative",
      "always the second bit",
      "not stored",
    ], answer: 1,
    hint: "MSB territory.",
    explanation: "The leftmost (most significant) bit carries the sign: 0 positive, 1 negative.",
  },
  {
    id: "ca-u1q8", topicId: "ca-floating-point", unit: 1, co: "CO1", level: "L2", source: "generated",
    prompt: "Floating point beats fixed point because it offers…",
    options: [
      "only more range",
      "only more precision",
      "both good range and good precision, by moving the radix point",
      "simpler hardware",
    ], answer: 2,
    hint: "Mass of the Earth AND mass of an atom.",
    explanation: "Shifting the point trades range and precision dynamically — fixed point freezes both at design time.",
  },
  {
    id: "ca-u1q9", topicId: "ca-ieee754", unit: 1, co: "CO1", level: "L2", source: "generated",
    prompt: "For 10.625 in IEEE 754 single precision, the stored exponent bits are 10000010 because…",
    options: [
      "the exponent 3 is biased by +127, giving 130",
      "10.625 rounds to 130",
      "the mantissa is 130 bits",
      "the sign bit is 130",
    ], answer: 0,
    hint: "Normalized as 1.010101 × 2³ — then what does the standard add to the 3?",
    explanation: "IEEE 754 stores exponent + 127: 3 + 127 = 130 = 10000010₂.",
  },
  {
    id: "ca-u1q10", topicId: "ca-gray", unit: 1, co: "CO1", level: "L1", source: "generated",
    prompt: "Which code changes only one bit between consecutive values?",
    options: ["BCD", "Excess-3", "Gray code", "ASCII"], answer: 2,
    hint: "It's called a unit-distance code.",
    explanation: "Gray code is the unit-distance, cyclic code — one bit per step, which encoders rely on.",
  },
  {
    id: "ca-u1q11", topicId: "ca-code-bcd", unit: 1, co: "CO1", level: "L2", source: "generated",
    prompt: "(45)₁₀ in BCD is…",
    options: ["101101", "0100 0101", "0101 0100", "1000 0100"], answer: 1,
    hint: "Each decimal digit gets its own 4 bits.",
    explanation: "4 → 0100 and 5 → 0101, digit by digit: 0100 0101. BCD never converts the whole number.",
  },
  {
    id: "ca-u1q12", topicId: "ca-excess3", unit: 1, co: "CO1", level: "L2", source: "generated",
    prompt: "The Excess-3 code of the decimal digit 6 is…",
    options: ["0110", "1001", "0011", "1100"], answer: 1,
    hint: "BCD of 6, plus 0011.",
    explanation: "0110 + 0011 = 1001 — each digit's XS-3 code is its BCD shifted up by three.",
  },
  {
    id: "ca-u1q13", topicId: "ca-from-decimal", unit: 1, co: "CO1", level: "L2", source: "generated",
    prompt: "In divide-and-collect conversion, the remainders are read…",
    options: ["top-down", "bottom-up", "in any order", "only the last one"], answer: 1,
    hint: "The first remainder is the units digit.",
    explanation: "The first division peels off the 1s place, so the answer assembles from the last remainder back to the first: bottom-up.",
  },
  {
    id: "ca-u1q14", topicId: "ca-ones-comp", unit: 1, co: "CO1", level: "L1", source: "generated",
    prompt: "The 1's complement operation is…",
    options: [
      "flip every bit, then add 1",
      "flip every bit — nothing more",
      "add 1 only",
      "flip only the sign bit",
    ], answer: 1,
    hint: "The +1 belongs to the OTHER complement.",
    explanation: "1's complement is the pure inversion; adding 1 afterwards produces the 2's complement.",
  },
  // ---- Sample end-term paper, Unit 1 questions (CO/L tags as printed) ----
  {
    id: "ca-ppq2", topicId: "ca-logic-gates", unit: 1, co: "CO1", level: "L1", source: "pastpaper",
    prompt: "The Boolean expression for an XNOR gate is:",
    options: ["AB + A'B'", "AB' + A'B", "A + B", "A ⊕ B"], answer: 0,
    hint: "XNOR is true when the inputs AGREE.",
    explanation: "Both-1 (AB) or both-0 (A'B') — agreement. AB' + A'B is XOR, its opposite.",
  },
  {
    id: "ca-ppq6", topicId: "ca-logic-gates", unit: 1, co: "CO1", level: "L2", source: "pastpaper",
    prompt: "How many truth table entries are required for a three-variable Boolean function?",
    options: ["4", "6", "8", "16"], answer: 2,
    hint: "2ⁿ.",
    explanation: "2³ = 8 rows cover every combination of three inputs.",
  },
  {
    id: "ca-ppq7", topicId: "ca-logic-gates", unit: 1, co: "CO1", level: "L2", source: "pastpaper",
    prompt: "Which logic gate is known as a universal gate?",
    options: ["AND", "OR", "XOR", "NAND"], answer: 3,
    hint: "Every other gate can be built from it alone.",
    explanation: "NAND (like NOR) is universal — combinations of NANDs implement any Boolean function.",
  },
  {
    id: "ca-ppq9", topicId: "ca-group-shortcuts", unit: 1, co: "CO1", level: "L4", source: "pastpaper",
    prompt: "Octal to binary conversion: (24)₈ = ?",
    options: ["(111101)₂", "(010100)₂", "(111100)₂", "(101010)₂"], answer: 1,
    hint: "Each octal digit becomes exactly 3 bits.",
    explanation: "2 → 010, 4 → 100, so (24)₈ = 010100₂.",
  },
  {
    id: "ca-ppq11", topicId: "ca-ones-comp", unit: 1, co: "CO2", level: "L2", source: "pastpaper",
    prompt: "The 1's complement of 1011001 is:",
    options: ["0100110", "1100110", "1010110", "0100111"], answer: 0,
    hint: "Flip every bit.",
    explanation: "Inverting each bit of 1011001 gives 0100110 — no +1 for 1's complement.",
  },
  {
    id: "ca-ppq18", topicId: "ca-from-decimal", unit: 1, co: "CO2", level: "L2", source: "pastpaper",
    prompt: "Which of the following is the correct binary representation of decimal 25?",
    options: ["11001", "10101", "10011", "11111"], answer: 0,
    hint: "16 + 8 + 1.",
    explanation: "25 = 16+8+1 = 11001₂ — the repeated-division example from the lesson.",
  },
  {
    id: "ca-ppq23", topicId: "ca-group-shortcuts", unit: 1, co: "CO1", level: "L4", source: "pastpaper",
    prompt: "The octal number (651.124)₈ is equivalent to ______",
    options: ["(1A9.2A)₁₆", "(1B0.10)₁₆", "(1A8.A3)₁₆", "(1B0.B0)₁₆"], answer: 0,
    hint: "Octal → binary in 3s, regroup in 4s → hex.",
    explanation: "651.124₈ = 110101001.001010100₂ = 0001 1010 1001 . 0010 1010₂ = 1A9.2A₁₆.",
  },
  {
    id: "ca-ppq24", topicId: "ca-group-shortcuts", unit: 1, co: "CO1", level: "L2", source: "pastpaper",
    prompt: "The hexadecimal number (1E.43)₁₆ is equivalent to…",
    options: ["(36.506)₈", "(36.206)₈", "(35.506)₈", "(35.206)₈"], answer: 1,
    hint: "Hex → binary in 4s, regroup in 3s → octal.",
    explanation: "1E.43₁₆ = 00011110.01000011₂ → 011110.010000110₂ = 36.206₈.",
  },
  {
    id: "ca-ppq26", topicId: "ca-code-bcd", unit: 1, co: "CO2", level: "L2", source: "pastpaper",
    prompt: "The BCD representation of the decimal number 13 is:",
    options: ["0001 0011", "1101", "1100 0011", "1010 0011"], answer: 0,
    hint: "Digit by digit — 1, then 3.",
    explanation: "1 → 0001, 3 → 0011 → 0001 0011. Plain binary 1101 is the trap: BCD codes each digit separately.",
  },
  // ---- Authored for Unit 2's circles (CO2/CO3 per syllabus mapping) ----
  {
    id: "ca-u2q1", topicId: "ca-instr-categories", unit: 2, co: "CO3", level: "L1", source: "generated",
    prompt: "Which category of instruction moves data without changing its value?",
    options: ["Data manipulation", "Data transfer", "Program control", "Arithmetic"], answer: 1,
    hint: "Move, don't compute.",
    explanation: "Data transfer instructions (MOV, LOAD, STORE, PUSH, POP…) relocate data unchanged; manipulation computes, program control redirects.",
  },
  {
    id: "ca-u2q2", topicId: "ca-data-manip", unit: 2, co: "CO3", level: "L2", source: "generated",
    prompt: "Shift, complement and AND belong to which family of data manipulation instructions?",
    options: [
      "Arithmetic only",
      "Shift is its own class; complement and AND are logical/bit-manipulation",
      "All three are arithmetic",
      "All three are program control",
    ], answer: 1,
    hint: "Three families: arithmetic, logical, shift.",
    explanation: "Data manipulation splits into arithmetic (ADD, SUB…), logical/bit (AND, OR, complement…) and shift (SHL, SHR, rotate) instructions.",
  },
  {
    id: "ca-u2q3", topicId: "ca-control-word", unit: 2, co: "CO2", level: "L2", source: "generated",
    prompt: "In a control word, the SELA and SELB fields choose…",
    options: [
      "the destination register",
      "the two source registers feeding the ALU buses",
      "the ALU operation",
      "the next instruction",
    ], answer: 1,
    hint: "A and B are the ALU's two input buses.",
    explanation: "SELA and SELB pick which registers drive bus A and bus B into the ALU; SELD picks the destination and OPR picks the operation.",
  },
  {
    id: "ca-u2q4", topicId: "ca-addr-immediate", unit: 2, co: "CO2", level: "L2", source: "generated",
    prompt: "In immediate addressing, the operand is…",
    options: [
      "in a register named by the instruction",
      "at the memory address given in the instruction",
      "inside the instruction itself, as part of the address field",
      "on top of the stack",
    ], answer: 2,
    hint: "No fetch needed — it's already here.",
    explanation: "Immediate mode carries the operand value in the instruction, so no extra memory reference is needed — fast, but the value is fixed.",
  },
  {
    id: "ca-u2q5", topicId: "ca-addr-direct-indirect", unit: 2, co: "CO2", level: "L4", source: "generated",
    prompt: "How many memory references does INDIRECT addressing need to reach the operand?",
    options: ["None", "One", "Two", "Three"], answer: 2,
    hint: "One to get the address, then…",
    explanation: "Indirect reads memory once to fetch the effective address, then again to fetch the operand — two references, versus direct's one.",
  },
  {
    id: "ca-u2q6", topicId: "ca-addr-register", unit: 2, co: "CO2", level: "L2", source: "generated",
    prompt: "Register INDIRECT addressing means the named register holds…",
    options: [
      "the operand itself",
      "the memory address of the operand",
      "the next instruction",
      "the ALU operation code",
    ], answer: 1,
    hint: "Value vs address — which one lives in the register here?",
    explanation: "In register-indirect mode the register holds the operand's ADDRESS (a pointer); plain register mode holds the value itself.",
  },
  // ---- Authored for Unit 3's circles (CO3 per syllabus mapping) ----
  {
    id: "ca-u3q1", topicId: "ca-stack-lifo", unit: 3, co: "CO3", level: "L1", source: "generated",
    prompt: "A stack follows which order?",
    options: ["FIFO", "LIFO", "Random", "Priority"], answer: 1,
    hint: "Think of a stack of plates.",
    explanation: "Last In, First Out — only the top is accessible, via PUSH and POP.",
  },
  {
    id: "ca-u3q2", topicId: "ca-stack-sp", unit: 3, co: "CO3", level: "L2", source: "generated",
    prompt: "In a descending stack, a PUSH operation…",
    options: [
      "increments SP, then stores",
      "decrements SP (SP = SP − 1), then stores at the new top",
      "stores, then decrements SP",
      "never moves SP",
    ], answer: 1,
    hint: "Make room first, in the direction the stack grows.",
    explanation: "A descending stack grows toward lower addresses: PUSH decrements SP to open a new top, then stores; POP reads then increments.",
  },
  {
    id: "ca-u3q3", topicId: "ca-rpn-notation", unit: 3, co: "CO3", level: "L2", source: "generated",
    prompt: "The RPN (postfix) form of (A + B) is…",
    options: ["+ A B", "A B +", "A + B", "B A -"], answer: 1,
    hint: "Operator after the operands.",
    explanation: "Postfix places the operator last: A B +. No parentheses are ever needed.",
  },
  {
    id: "ca-u3q4", topicId: "ca-rpn-stack", unit: 3, co: "CO3", level: "L4", source: "generated",
    prompt: "Evaluating 3 5 + 2 * with a stack gives…",
    options: ["13", "16", "30", "10"], answer: 1,
    hint: "Numbers push; operators pop two, compute, push back.",
    explanation: "3 5 + leaves 8 on the stack; 2 pushes; * pops 8,2 and pushes 16 — the lesson's worked trace.",
  },
  {
    id: "ca-u3q5", topicId: "ca-fmt-01", unit: 3, co: "CO3", level: "L2", source: "generated",
    prompt: "Zero-address instructions are natural on…",
    options: [
      "accumulator machines",
      "stack-based CPUs like the JVM",
      "three-address RISC machines",
      "DMA controllers",
    ], answer: 1,
    hint: "Where do their operands implicitly come from?",
    explanation: "With operands implicit on the stack, no addresses are needed — the JVM and HP calculators work this way.",
  },
  {
    id: "ca-u3q6", topicId: "ca-fmt-23", unit: 3, co: "CO3", level: "L2", source: "generated",
    prompt: "ADD A, B (result overwrites A) is which instruction format?",
    options: ["Zero-address", "One-address", "Two-address", "Three-address"], answer: 2,
    hint: "Count the named operands.",
    explanation: "Two named operands with the result replacing one — the two-address format of general-register machines.",
  },
  {
    id: "ca-u3q7", topicId: "ca-jumps-loops", unit: 3, co: "CO3", level: "L2", source: "generated",
    prompt: "A conditional branch like JNZ decides using…",
    options: ["the stack pointer", "the flags register", "the DMA controller", "ROM"], answer: 1,
    hint: "Zero, Carry, Sign, Overflow.",
    explanation: "Condition codes in the flags register, set by earlier operations, steer conditional jumps.",
  },
  {
    id: "ca-u3q8", topicId: "ca-call-ret", unit: 3, co: "CO3", level: "L2", source: "generated",
    prompt: "During a subroutine CALL, the return address is stored…",
    options: ["in the ALU", "on the stack", "in ROM", "in the cache"], answer: 1,
    hint: "It must come back off in LIFO order when RET runs.",
    explanation: "CALL pushes the return address onto the stack; RET pops it — nested calls unwind correctly because of LIFO.",
  },
  {
    id: "ca-u3q9", topicId: "ca-interrupts", unit: 3, co: "CO3", level: "L1", source: "generated",
    prompt: "An interrupt triggered by the INT instruction is…",
    options: ["a hardware interrupt", "a software interrupt", "non-maskable", "a page fault"], answer: 1,
    hint: "It came from code, not from a device.",
    explanation: "Instruction-triggered interrupts are software interrupts; external events (keyboard, failures) raise hardware interrupts.",
  },
  {
    id: "ca-u3q10", topicId: "ca-flow-anatomy", unit: 3, co: "CO3", level: "L1", source: "generated",
    prompt: "The Program Counter (PC) holds…",
    options: [
      "the current instruction",
      "the address of the next instruction to be executed",
      "the top of the stack",
      "the ALU result",
    ], answer: 1,
    hint: "It auto-increments after each instruction.",
    explanation: "The PC always points at the NEXT instruction's address; the current instruction sits in the IR.",
  },
  // ---- Authored for Unit 4's circles (CO4 per syllabus mapping) ----
  {
    id: "ca-u4q1", topicId: "ca-sub-2comp", unit: 4, co: "CO4", level: "L2", source: "generated",
    prompt: "Computers subtract B from A by…",
    options: [
      "a dedicated subtraction circuit",
      "adding the 2's complement of B to A",
      "swapping the operands",
      "repeated decrement",
    ], answer: 1,
    hint: "One adder, two jobs.",
    explanation: "A − B = A + (2's complement of B) — the complement trick lets one parallel adder do both operations.",
  },
  {
    id: "ca-u4q2", topicId: "ca-add-signed", unit: 4, co: "CO4", level: "L2", source: "generated",
    prompt: "(+10) + (+3) in 5-bit signed binary (0 1010 + 0 0011) equals…",
    options: ["0 1101", "1 1101", "0 1011", "1 0111"], answer: 0,
    hint: "Add the magnitudes; the sign bit stays 0.",
    explanation: "01010 + 00011 = 01101 = +13, sign bit 0 throughout.",
  },
  {
    id: "ca-u4q3", topicId: "ca-addsub-hw", unit: 4, co: "CO4", level: "L2", source: "generated",
    prompt: "In the add/subtract hardware, mode control M = 0 makes the circuit output…",
    options: ["A − B", "A + B", "B − A", "A + B' + 1"], answer: 1,
    hint: "M = 0 passes B through unchanged with carry-in 0.",
    explanation: "M=0: plain B and carry 0 → A + B. M=1 complements B with carry 1 → A − B.",
  },
  {
    id: "ca-u4q4", topicId: "ca-addsub-hw", unit: 4, co: "CO4", level: "L1", source: "generated",
    prompt: "Which flip-flop receives the adder's output carry?",
    options: ["AVF", "E", "As", "M"], answer: 1,
    hint: "AVF is busy holding the overflow.",
    explanation: "E stores the output carry; AVF holds the overflow bit; As/Bs are the sign flip-flops.",
  },
  {
    id: "ca-u4q5", topicId: "ca-booth-rules", unit: 4, co: "CO4", level: "L2", source: "generated",
    prompt: "In Booth's algorithm, the bit pair 01 triggers…",
    options: [
      "shift only",
      "add the multiplicand to A, then shift",
      "subtract the multiplicand, then shift",
      "end of algorithm",
    ], answer: 1,
    hint: "10 is the subtractor; what's its mirror?",
    explanation: "01 adds M to A before the arithmetic right shift; 10 subtracts; 00/11 only shift.",
  },
  {
    id: "ca-u4q6", topicId: "ca-booth-idea", unit: 4, co: "CO4", level: "L1", source: "generated",
    prompt: "Booth's algorithm is designed to multiply…",
    options: [
      "unsigned numbers only",
      "signed numbers in 2's complement representation",
      "BCD numbers",
      "floating point numbers",
    ], answer: 1,
    hint: "Invented in 1951 precisely for signed arithmetic.",
    explanation: "Booth (1951) multiplies signed 2's-complement operands directly, with fewer additions via shift runs.",
  },
  {
    id: "ca-u4q7", topicId: "ca-mult-shiftadd", unit: 4, co: "CO4", level: "L1", source: "generated",
    prompt: "Basic signed-magnitude binary multiplication is performed by successive…",
    options: [
      "divide and conquer",
      "shift and add operations",
      "complement and swap",
      "compare and branch",
    ], answer: 1,
    hint: "Long multiplication, base 2.",
    explanation: "Each multiplier bit contributes a shifted copy of the multiplicand — shift-and-add is the whole method.",
  },
  {
    id: "ca-u4q8", topicId: "ca-booth-run", unit: 4, co: "CO4", level: "L4", source: "generated",
    prompt: "Running Booth's algorithm for 7 × 3 (4-bit registers), the final product is read from…",
    options: [
      "register A alone",
      "the register pair A:Q — 0001 0101 = 21",
      "register Q alone",
      "the count register",
    ], answer: 1,
    hint: "Two 4-bit registers hold one 8-bit product.",
    explanation: "When count reaches 0, A:Q together hold the double-width signed product: 0001 0101 = 21.",
  },
  // ---- Authored for Unit 5's circles (CO5 per syllabus mapping) ----
  {
    id: "ca-u5q1", topicId: "ca-io-interface", unit: 5, co: "CO5", level: "L2", source: "generated",
    prompt: "The main functions of the I/O interface are…",
    options: [
      "data conversion, synchronization, device selection",
      "fetch, decode, execute",
      "push, pop, call",
      "paging, mapping, caching",
    ], answer: 0,
    hint: "It exists to resolve the CPU-peripheral mismatches.",
    explanation: "The interface converts signals, synchronises speeds, and selects the addressed device — the slides' exact trio.",
  },
  {
    id: "ca-u5q2", topicId: "ca-io-bus", unit: 5, co: "CO5", level: "L2", source: "generated",
    prompt: "Which I/O command activates a peripheral and tells it what to do?",
    options: ["Status", "Control", "Data input", "Data output"], answer: 1,
    hint: "It commands; another one merely asks how things are going.",
    explanation: "The control command activates and instructs; status tests conditions; data input/output move the data itself.",
  },
  {
    id: "ca-u5q3", topicId: "ca-async-strobe", unit: 5, co: "CO5", level: "L2", source: "generated",
    prompt: "The strobe method's weakness is that…",
    options: [
      "it needs too many wires",
      "the initiating unit can't know whether the other unit actually responded",
      "it only works for printers",
      "it requires a shared clock",
    ], answer: 1,
    hint: "One control line commands — but who confirms?",
    explanation: "With a single control line there is no acknowledgment; handshaking adds the reply line that confirms each transfer.",
  },
  {
    id: "ca-u5q4", topicId: "ca-handshake", unit: 5, co: "CO5", level: "L2", source: "generated",
    prompt: "In source-initiated handshaking, the destination replies with…",
    options: ["a strobe pulse", "the data-accepted signal", "an interrupt", "a page fault"], answer: 1,
    hint: "The second wire's whole purpose.",
    explanation: "Source raises data-valid; destination confirms with data-accepted; then both reset — every transfer acknowledged.",
  },
  {
    id: "ca-u5q5", topicId: "ca-transfer-modes", unit: 5, co: "CO5", level: "L2", source: "generated",
    prompt: "Interrupt-initiated I/O improves on programmed I/O because…",
    options: [
      "the CPU polls faster",
      "the CPU works on its task and is only interrupted when the device is ready",
      "it removes the interface",
      "data goes through the cache",
    ], answer: 1,
    hint: "Who watches the flag in each scheme?",
    explanation: "No busy-wait loop: the device signals readiness itself, so CPU time isn't wasted monitoring flags.",
  },
  {
    id: "ca-u5q6", topicId: "ca-dma", unit: 5, co: "CO5", level: "L2", source: "generated",
    prompt: "In DMA, data moves between device and memory…",
    options: [
      "through CPU registers",
      "directly, with the DMA controller borrowing the system buses",
      "one word per interrupt",
      "only at boot",
    ], answer: 1,
    hint: "The CPU steps aside entirely.",
    explanation: "The controller takes the address/data/control buses and streams data directly — independent of the CPU.",
  },
  {
    id: "ca-u5q7", topicId: "ca-priority-daisy", unit: 5, co: "CO5", level: "L2", source: "generated",
    prompt: "In daisy chaining, the device that sent the interrupt request has…",
    options: ["PI = 0, PO = 1", "PI = 1, PO = 0", "PI = PO = 1", "PI = PO = 0"], answer: 1,
    hint: "Acknowledge arrived, and stopped there.",
    explanation: "INTACK reached it (PI=1) and it blocked the chain (PO=0) while placing its VAD on the bus.",
  },
  {
    id: "ca-u5q8", topicId: "ca-peripherals", unit: 5, co: "CO5", level: "L1", source: "generated",
    prompt: "A device under the direct control of the computer is said to be connected…",
    options: ["offline", "online", "in parallel", "asynchronously"], answer: 1,
    hint: "The deck's one-word vocabulary flag.",
    explanation: "Online means under the computer's direct control — the deck's definition for connected peripherals.",
  },
  // ---- Authored for Unit 6's circles (CO6 per syllabus mapping) ----
  {
    id: "ca-u6q1", topicId: "ca-mem-hierarchy", unit: 6, co: "CO6", level: "L2", source: "generated",
    prompt: "Ordered fastest to slowest, the hierarchy is…",
    options: [
      "registers → cache → main memory → auxiliary",
      "auxiliary → main → cache → registers",
      "cache → registers → auxiliary → main",
      "main → cache → registers → auxiliary",
    ], answer: 0,
    hint: "Smallest and closest to the CPU is fastest.",
    explanation: "Registers, then cache, then RAM, then disks/tapes — speed falls and size grows down the pyramid.",
  },
  {
    id: "ca-u6q2", topicId: "ca-mem-hierarchy", unit: 6, co: "CO6", level: "L1", source: "generated",
    prompt: "Auxiliary memory access time compared to main memory is roughly…",
    options: ["the same", "10× slower", "1000× slower", "1000× faster"], answer: 2,
    hint: "It sits at the bottom of the hierarchy for a reason.",
    explanation: "The slides put auxiliary access at about 1000 times main memory's — which is why it's the bottom layer.",
  },
  {
    id: "ca-u6q3", topicId: "ca-main-ram-rom", unit: 6, co: "CO6", level: "L2", source: "generated",
    prompt: "Which is TRUE of ROM?",
    options: [
      "Volatile and writable",
      "Non-volatile, read-only, holds the bootstrap loader",
      "Faster than registers",
      "Cleared on every reboot",
    ], answer: 1,
    hint: "It must survive power-off to do its one job.",
    explanation: "ROM keeps its contents without power and only reads — which is why the boot program lives there.",
  },
  {
    id: "ca-u6q4", topicId: "ca-map-set", unit: 6, co: "CO6", level: "L2", source: "generated",
    prompt: "Set-associative mapping is a compromise between…",
    options: [
      "RAM and ROM",
      "direct mapping and fully associative mapping",
      "cache and virtual memory",
      "SRAM and DRAM",
    ], answer: 1,
    hint: "Direct-map to a set, then search only its K lines.",
    explanation: "It keeps direct mapping's cheap indexing but allows K choices per set, avoiding full-search hardware costs.",
  },
  {
    id: "ca-u6q5", topicId: "ca-virtual-mem", unit: 6, co: "CO6", level: "L2", source: "generated",
    prompt: "Virtual memory's core promise is…",
    options: [
      "faster registers",
      "the illusion of a large memory despite a small physical RAM, via pages swapped from disk",
      "eliminating the cache",
      "read-only main memory",
    ], answer: 1,
    hint: "Pages, swap space, page faults.",
    explanation: "The OS pages memory between RAM and disk on demand, so programs can exceed physical RAM safely.",
  },
  {
    id: "ca-u6q6", topicId: "ca-cache-hit", unit: 6, co: "CO6", level: "L4", source: "generated",
    prompt: "With 950 cache hits out of 1000 total memory references, the hit ratio is…",
    options: ["0.05", "0.95", "19", "950"], answer: 1,
    hint: "Hit / (Hit + Miss).",
    explanation: "950/(950+50) = 0.95 — hits over total references, always between 0 and 1.",
  },
  {
    id: "ca-u6q7", topicId: "ca-map-direct", unit: 6, co: "CO6", level: "L2", source: "generated",
    prompt: "In direct mapping, the address's INDEX field is used to…",
    options: [
      "verify the data",
      "select the one cache line where the block may live",
      "store the data",
      "choose a replacement victim",
    ], answer: 1,
    hint: "Low bits find; high bits verify.",
    explanation: "The index (lower bits) selects the line; the tag (higher bits) is stored and compared to confirm the hit.",
  },
  {
    id: "ca-u6q8", topicId: "ca-cam", unit: 6, co: "CO6", level: "L1", source: "generated",
    prompt: "Content Addressable Memory retrieves items by…",
    options: [
      "unique address",
      "matching part of their content",
      "sequential order",
      "page number",
    ], answer: 1,
    hint: "Its other name is associative memory.",
    explanation: "CAM searches all words in parallel for a content match — the argument, key and match registers do the work.",
  },
  {
    id: "ca-u6q9", topicId: "ca-mem-access", unit: 6, co: "CO6", level: "L2", source: "generated",
    prompt: "Magnetic tape uses which memory access method?",
    options: ["Random", "Sequential", "Direct", "Associative"], answer: 1,
    hint: "You must wind past everything before your data.",
    explanation: "Tape reaches locations in order — sequential access; disks are direct; main memory is random.",
  },
  {
    id: "ca-u6q10", topicId: "ca-mem-chips", unit: 6, co: "CO6", level: "L4", source: "generated",
    prompt: "A 128 × 8 RAM chip needs how many address lines?",
    options: ["8", "7", "128", "9"], answer: 1,
    hint: "2 to what power gives 128?",
    explanation: "2⁷ = 128 words, so a 7-bit unidirectional address bus suffices; the 512-byte ROM needs 9.",
  },
  // ---- Sample end-term paper, Unit 2 questions (CO/L tags as printed) ----
  {
    id: "ca-ppq4", topicId: "ca-addr-direct-indirect", unit: 2, co: "CO2", level: "L2", source: "pastpaper",
    prompt: "What addressing mode allows you to directly specify the memory address of an operand in the instruction?",
    options: ["Immediate", "Register", "Direct", "Indirect"], answer: 2,
    hint: "The address field IS the effective address.",
    explanation: "Direct (absolute) addressing carries the operand's memory address in the instruction — one memory reference.",
  },
  {
    id: "ca-ppq5", topicId: "ca-cpu-alu", unit: 2, co: "CO1", level: "L2", source: "pastpaper",
    prompt: "Who designed the computer's fundamental architecture?",
    options: ["Pascal", "C. Babbage", "John von Neumann", "None of these"], answer: 2,
    hint: "The stored-program architecture bears his name.",
    explanation: "The von Neumann architecture — program and data in one memory — is the fundamental design.",
  },
  {
    id: "ca-ppq15", topicId: "ca-cpu-alu", unit: 2, co: "CO1", level: "L4", source: "pastpaper",
    prompt: "The processor's \"heart,\" which carries out numerous functions, is the…",
    options: ["Arithmetic and Logic Unit", "Circuit boards", "Control Unit", "Memory"], answer: 0,
    hint: "It does the computing itself.",
    explanation: "The ALU performs the arithmetic and logical operations — the computational heart of the CPU.",
  },
  {
    id: "ca-ppq17", topicId: "ca-instr-categories", unit: 2, co: "CO3", level: "L2", source: "pastpaper",
    prompt: "Which of the following is a data transfer instruction?",
    options: ["ADD", "MOV", "CMP", "SUB"], answer: 1,
    hint: "Which one moves data without changing it?",
    explanation: "MOV transfers data unchanged; ADD/SUB manipulate, CMP tests.",
  },
  {
    id: "ca-ppq22", topicId: "ca-addr-extended", unit: 2, co: "CO2", level: "L6", source: "pastpaper",
    prompt: "Which addressing mode calculates the effective address of the operand using the value in the program counter (PC)?",
    options: ["Immediate", "PC-relative", "Indexed", "Base-indexed"], answer: 1,
    hint: "Its name says which register anchors the address.",
    explanation: "Relative (PC-relative) addressing adds an offset to the program counter — used for branches.",
  },
  // ---- Sample end-term paper, Unit 3 questions (CO/L tags as printed) ----
  {
    id: "ca-ppq1", topicId: "ca-fmt-23", unit: 3, co: "CO3", level: "L2", source: "pastpaper",
    prompt: "Which of the following is NOT a valid instruction format?",
    options: ["Zero-address", "One-address", "Two-address", "Four-address"], answer: 3,
    hint: "Count how many formats the comparison table actually has.",
    explanation: "The standard formats are zero through three address; four-address is the invented option.",
  },
  // ---- Sample end-term paper, Unit 4 questions (CO/L tags as printed) ----
  {
    id: "ca-ppq19", topicId: "ca-mult-shiftadd", unit: 4, co: "CO4", level: "L2", source: "pastpaper",
    prompt: "The shift-and-add multiplication method is based on:",
    options: [
      "Bitwise shifting and addition",
      "Repeated subtraction",
      "Dividing and multiplying with powers of two",
      "None of the above",
    ], answer: 0,
    hint: "Its name is the method.",
    explanation: "Each multiplier bit adds a shifted copy of the multiplicand — shifting plus addition.",
  },
  {
    id: "ca-ppq20", topicId: "ca-booth-idea", unit: 4, co: "CO4", level: "L2", source: "pastpaper",
    prompt: "Booth's multiplication algorithm is used for:",
    options: [
      "Efficient division",
      "Efficient multiplication of binary numbers",
      "Decimal addition",
      "Floating-point multiplication",
    ], answer: 1,
    hint: "Signed 2's-complement operands, fewer additions.",
    explanation: "Booth multiplies signed binary numbers efficiently using shift runs to skip additions.",
  },
  {
    id: "ca-ppq25", topicId: "ca-booth-rules", unit: 4, co: "CO4", level: "L6", source: "pastpaper",
    prompt: "What is the main advantage of Booth's algorithm in binary multiplication?",
    options: [
      "Reduced number of additions",
      "Reduced number of shifts",
      "Reduced memory usage",
      "Better precision",
    ], answer: 0,
    hint: "Runs of identical bits cost only shifts.",
    explanation: "Booth's recoding turns runs of 1s into a subtract-and-add pair, cutting the number of additions.",
  },
  // ---- Sample end-term paper, Unit 5 questions (CO/L tags as printed) ----
  {
    id: "ca-ppq3", topicId: "ca-transfer-modes", unit: 5, co: "CO5", level: "L2", source: "pastpaper",
    prompt: "Which of the following is not a mode of data transfer in computer systems?",
    options: ["Programmed I/O", "Direct Memory Access (DMA)", "Memory-mapped I/O", "Bus communication"], answer: 3,
    hint: "Three real modes plus one made-up phrase.",
    explanation: "Programmed, interrupt-initiated/memory-mapped I/O and DMA are genuine; 'bus communication' is not a transfer mode.",
  },
  {
    id: "ca-ppq8", topicId: "ca-io-interface", unit: 5, co: "CO5", level: "L2", source: "pastpaper",
    prompt: "Which of the following is NOT a role of the I/O interface?",
    options: [
      "Data conversion between different formats",
      "Managing communication between devices",
      "Connecting the CPU to RAM",
      "Generating control signals for peripherals",
    ], answer: 2,
    hint: "One option belongs to the memory bus, not I/O.",
    explanation: "CPU↔RAM is the memory bus's job; the I/O interface faces peripherals.",
  },
  {
    id: "ca-ppq13", topicId: "ca-async-strobe", unit: 5, co: "CO5", level: "L2", source: "pastpaper",
    prompt: "Which of the following is a key feature of asynchronous transfer?",
    options: [
      "Requires a clock signal",
      "Data is transferred in bursts",
      "Each data unit is sent with a start and stop bit",
      "Data transfer speed is fixed",
    ], answer: 2,
    hint: "No shared clock — so each unit carries its own timing.",
    explanation: "Asynchronous transfer frames each unit with start/stop signalling instead of a common clock.",
  },
  {
    id: "ca-ppq14", topicId: "ca-async-strobe", unit: 5, co: "CO5", level: "L2", source: "pastpaper",
    prompt: "Which of the following is true about synchronous data transfer?",
    options: [
      "Data is transferred without any timing coordination",
      "It requires a shared clock signal between sender and receiver",
      "It is slower than asynchronous transfer",
      "It does not require synchronization signals",
    ], answer: 1,
    hint: "The word 'synchronous' is the clue.",
    explanation: "Synchronous transfer runs sender and receiver off one shared clock — the opposite of start/stop framing.",
  },
  // ---- Sample end-term paper, Unit 6 questions (CO/L tags as printed) ----
  {
    id: "ca-ppq10", topicId: "ca-mem-hierarchy", unit: 6, co: "CO6", level: "L2", source: "pastpaper",
    prompt: "The purpose of the memory hierarchy in a computer system is to:",
    options: [
      "Increase memory access speed",
      "Minimize data storage",
      "Reduce CPU processing",
      "None of these",
    ], answer: 0,
    hint: "Why layer fast-small over slow-big at all?",
    explanation: "The hierarchy exists to raise effective access speed at reasonable cost by keeping hot data in fast layers.",
  },
  {
    id: "ca-ppq12", topicId: "ca-main-ram-rom", unit: 6, co: "CO1", level: "L4", source: "pastpaper",
    prompt: "Which memory holds the boot sector files for the system?",
    options: ["RAM", "ROM", "Cache", "Register"], answer: 1,
    hint: "It must survive the power being off.",
    explanation: "The bootstrap loader lives in non-volatile ROM — RAM is empty at power-on.",
  },
  {
    id: "ca-ppq16", topicId: "ca-mem-hierarchy", unit: 6, co: "CO1", level: "L4", source: "pastpaper",
    prompt: "In the memory hierarchy, which of the following has the fastest speed?",
    options: ["Memory", "CPU register", "Primary memory", "Memory cache"], answer: 1,
    hint: "Inside the CPU itself.",
    explanation: "Registers top the hierarchy — faster even than cache.",
  },
  {
    id: "ca-ppq21", topicId: "ca-aux-memory", unit: 6, co: "CO1", level: "L4", source: "pastpaper",
    prompt: "Which of the following memories is used in a digital camera?",
    options: ["Virtual memory", "Flash memory", "Main memory", "Cache memory"], answer: 1,
    hint: "Non-volatile, removable, solid-state.",
    explanation: "Cameras store photos on flash memory cards — non-volatile solid-state storage.",
  },
];

export const cse46d = buildCourseBundle(
  {
    id: "cse46d",
    code: "CSE46D",
    title: "Computer Architecture",
    sections: [sectionU1A, sectionU1B, sectionU2, sectionU3, sectionU4, sectionU5, sectionU6],
    pairedLab: {},
  },
  examBank
);
